/*
 * Company: ChowDSP
 * Effect Name: ChowCentaur
 * Description: A digital emulation of the public circuit for the Klon Centaur.
 *
 * This file was auto-generated by Aviate Audio Effect Creator for the Multiverse.
 */
#include <cmath>
#include "Aviate/LibBasicFunctions.h"
#include "ChowCentaur.h"

using namespace Aviate;

namespace ChowDSP_ChowCentaur {

void ChowCentaur::mapMidiControl(int parameter, int midiCC, int midiChannel)
{
    if (parameter >= NUM_CONTROLS) {
        return ; // Invalid midi parameter
    }
    m_midiConfig[parameter][MIDI_CHANNEL] = midiChannel;
    m_midiConfig[parameter][MIDI_CONTROL] = midiCC;
}

void ChowCentaur::setParam(int paramIndex, float paramValue)
{
    switch(paramIndex) {
    case 0 : bypass( (paramValue - 0.000000) / (1.000000 - 0.000000) ); break;
    case 1 : volume( (paramValue - 0.000000) / (10.000000 - 0.000000) ); break;
    case 2 : gain( (paramValue - 0.000000) / (10.000000 - 0.000000) ); break;
    case 3 : treble( (paramValue - 0.000000) / (10.000000 - 0.000000) ); break;
    case 4 : modelinputbuf( (paramValue - 0.000000) / (1.000000 - 0.000000) ); break;
    case 5 : modeloutputbuf( (paramValue - 0.000000) / (1.000000 - 0.000000) ); break;
    default : break;
    }
}

float ChowCentaur::getUserParamValue(int paramIndex, float normalizedParamValue)
{
    switch(paramIndex) {
    case 0 : return ( ((1.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // bypass
    case 1 : return ( ((10.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // volume
    case 2 : return ( ((10.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // gain
    case 3 : return ( ((10.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // treble
    case 4 : return ( ((1.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // modelinputbuf
    case 5 : return ( ((1.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // modeloutputbuf
    default : return 0.0f;
    }
}

void ChowCentaur::processMidi(int channel, int control, int value)
{
    float val = (float)value / 127.0f;

    if ((m_midiConfig[Bypass_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Bypass_e][MIDI_CONTROL] == control)) {
        bypass(val);
        return;
    }

    if ((m_midiConfig[Volume_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Volume_e][MIDI_CONTROL] == control)) {
        volume(val);
        return;
    }

    if ((m_midiConfig[Gain_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Gain_e][MIDI_CONTROL] == control)) {
        gain(val);
        return;
    }

    if ((m_midiConfig[Treble_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Treble_e][MIDI_CONTROL] == control)) {
        treble(val);
        return;
    }

    if ((m_midiConfig[ModelInputBuf_e][MIDI_CHANNEL] == channel) && (m_midiConfig[ModelInputBuf_e][MIDI_CONTROL] == control)) {
        modelinputbuf(val);
        return;
    }

    if ((m_midiConfig[ModelOutputBuf_e][MIDI_CHANNEL] == channel) && (m_midiConfig[ModelOutputBuf_e][MIDI_CONTROL] == control)) {
        modeloutputbuf(val);
        return;
    }

}

audio_block_t* ChowCentaur::m_basicInputCheck(audio_block_t* inputAudioBlock, unsigned outputChannel)
{
    // Check if effect is disabled
    if (m_enable == false) {
        // do not transmit or process any audio, return as quickly as possible after releasing the inputs
        if (inputAudioBlock) { release(inputAudioBlock); }
        return nullptr; // disabled, no further EFX processing in update()
    }  // end of enable check

    // check if effect is in bypass
    if (m_bypass == true) {
        // drive input directly to the specified output. ie. bypass
        if (inputAudioBlock != nullptr) {
            // valid input, drive to outputChannel if specified
            if (outputChannel >= 0) {
                transmit(inputAudioBlock, outputChannel); // drive to specified output
            }
            release(inputAudioBlock); // release the input block as we are done with it
        } else { // invalid input block, allocate a block and drive silence if specified
            if (outputChannel >= 0) {
                audio_block_t* silenceBlock = allocate();
                if (silenceBlock) {
                    clearAudioBlock(silenceBlock);  // create silence in the buffer
                    transmit(silenceBlock, outputChannel);
                    release(silenceBlock);
                }
            }
        }
        return nullptr;  // bypassed, no further EFX processing in update()
    }  // end of bypass check

    // If not disabled or bypassed, create silence if the input block is invalid then
    // return the valid audio block so update() can continue.
    if (inputAudioBlock == nullptr) {
        inputAudioBlock = allocate();
        if (inputAudioBlock == nullptr) { return nullptr; } // check if allocate was unsuccessful
        // else
        clearAudioBlock(inputAudioBlock);
    }
    return inputAudioBlock; // inputAudioBLock is valid and ready for update() processing
}

const uint8_t rblk[256] = TEENSY_AUDIO_BLOCK;
const uint8_t* ChowCentaur::getRblk() { return rblk; }
static constexpr char PROGMEM ChowCentaur_name[] = {0x43, 0x68, 0x6f, 0x77, 0x44, 0x53, 0x50, 0x3a, 0x43, 0x68, 0x6f, 0x77, 0x43, 0x65, 0x6e, 0x74, 0x61, 0x75, 0x72, 0x0};
const char* ChowCentaur::getName() { return ChowCentaur_name; }

}
